name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install pandoc + tex
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
        sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb
        sudo apt-get update
        sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  docker-push:
    runs-on: ubuntu-latest
    needs: build
    steps:  
    - name: docker-build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ DOCKER_USERNAME }}
        password: ${{ DOCKER_PASSWORD }}
        repository: dennybritz/ablog-api-local
        tag_with_sha: true
        tag_with_ref: true
